"""
Django settings for HomeRental project.
Configuration for home rental web application.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see:
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# ===== PATH CONFIGURATION =====
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===== SECURITY SETTINGS =====
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^jfqx_ra3f5!_zp0#rr50cy5qav3sxx)hm*ob&v^_%4)3rm%5e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ['true', '1', 'yes']

# Hosts/origins allowed for both HTTP and WebSocket traffic.
# Override in production with ALLOWED_HOSTS environment variable
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = ['home-rental-ogd2.onrender.com']


# ===== INSTALLED APPLICATIONS =====
# List of installed apps - order matters for apps with templates/static files
INSTALLED_APPS = [
    'django.contrib.admin',  # Django admin interface
    'django.contrib.auth',  # User authentication system
    'django.contrib.contenttypes',  # Content types framework
    'django.contrib.sessions',  # Session management
    'django.contrib.messages',  # Message framework for user notifications
    'daphne',  # Daphne provides the ASGI-aware runserver command used by Channels.
    'django.contrib.staticfiles',  # Static files management
    'channels',  # Django Channels for WebSocket support
    'chat',  # Accepted-booking chat app
    'home',
    'payments',  # Our home rental app
]

# ===== MIDDLEWARE CONFIGURATION =====
# Middleware processes requests and responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Security enhancements
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files serving
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session management
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # User authentication
    'django.contrib.messages.middleware.MessageMiddleware',  # Message display
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]

# ===== URL CONFIGURATION =====
ROOT_URLCONF = 'HomeRental.urls'  # Root URL configuration
ASGI_APPLICATION = 'HomeRental.asgi.application'  # ASGI app used by Channels/uvicorn

# ===== TEMPLATE CONFIGURATION =====
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates directory
        'APP_DIRS': True,  # Look for templates in app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Adds request to context
                'django.contrib.auth.context_processors.auth',  # Adds user to context
                'django.contrib.messages.context_processors.messages',  # Adds messages to context
                'home.context_processors.unread_notifications_count',  # Custom context processor for notifications
            ],
        },
    },
]

# ===== WSGI APPLICATION =====
WSGI_APPLICATION = 'HomeRental.wsgi.application'  # WSGI application for web servers


# ===== CHANNELS / WEBSOCKETS =====
# Default to an in-memory layer for local development. Set CHANNEL_REDIS_URL in
# production to use a shared Redis-backed layer across multiple workers.
CHANNEL_REDIS_URL = os.environ.get("CHANNEL_REDIS_URL", "").strip()

if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# ===== DATABASE CONFIGURATION =====
# Priority: PostgreSQL (Render) > MySQL > SQLite (local development)
DB_ENGINE = os.environ.get("DB_ENGINE", "").strip().lower()
DB_NAME = os.environ.get("DB_NAME", "").strip()
DB_USER = os.environ.get("DB_USER", "").strip()
DB_PASSWORD = os.environ.get("DB_PASSWORD", "").strip()
DB_HOST = os.environ.get("DB_HOST", "").strip()
DB_PORT = os.environ.get("DB_PORT", "").strip()

# PostgreSQL Configuration (Render Production)
if DB_ENGINE in {"postgresql", "django.db.backends.postgresql", "psycopg2"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME or "home_rental_db",
            "USER": DB_USER or "postgres",
            "PASSWORD": DB_PASSWORD or "",
            "HOST": DB_HOST or "localhost",
            "PORT": DB_PORT or "5432",
            "OPTIONS": {
                "sslmode": "require" if not DEBUG else "disable",
            } if DB_HOST else {},
        }
    }
# MySQL Configuration (Alternative production)
elif DB_ENGINE in {"mysql", "django.db.backends.mysql"} or (DB_ENGINE == "" and DB_NAME and "mysql" in str(DB_HOST or "").lower()):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": DB_NAME or "home_rental",
            "USER": DB_USER or "root",
            "PASSWORD": DB_PASSWORD or "",
            "HOST": DB_HOST or "127.0.0.1",
            "PORT": DB_PORT or "3306",
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
# SQLite Configuration (Local Development - Default)
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# ===== PASSWORD VALIDATION =====
# Password validators to enforce strong passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        # Check password doesn't match user attributes (username, email)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Minimum password length (default: 8 characters)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # Check against top 20,000 common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Check password isn't entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===== INTERNATIONALIZATION SETTINGS =====
# Language and timezone configuration
LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Default timezone (change to your timezone if needed)

USE_I18N = True  # Enable i18n framework

USE_TZ = True  # Use timezone-aware datetime


# ===== STATIC FILES CONFIGURATION =====
# CSS, JavaScript, Images served by web server
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'  # URL prefix for static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Static files collection directory for production
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Additional static files directories
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# ===== MEDIA FILES CONFIGURATION =====
# User-uploaded files (images, documents, etc.)
MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Physical location of media files


# ===== AUTHENTICATION SETTINGS =====
LOGIN_URL = '/accounts/login'  # URL to redirect to for login

LOGIN_REDIRECT_URL = '/home/'  # URL to redirect to after successful login
LOGOUT_REDIRECT_URL = '/home/'  # URL to redirect to after logout


# for the email settings 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ['true', '1', 'yes']
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'shriram77890@gmail.com')       # Your Gmail
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'yaxr gdas ipss vksj')      # Use App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# for the payment methods 
ESEWA_MERCHANT_ID = "EPAYTEST"
ESEWA_SECRET_KEY = os.environ.get("ESEWA_SECRET_KEY", "8gBm/:&EnhH.1/q")
ESEWA_SIGNED_FIELD_NAMES = os.environ.get(
    "ESEWA_SIGNED_FIELD_NAMES",
    "total_amount,transaction_uuid,product_code",
)
ESEWA_FORM_URL = os.environ.get(
    "ESEWA_FORM_URL",
    "https://rc-epay.esewa.com.np/api/epay/main/v2/form",
)

SUCCESS_URL = os.environ.get("SUCCESS_URL", "http://127.0.0.1:8000/payment/success/")
FAILURE_URL = os.environ.get("FAILURE_URL", "http://127.0.0.1:8000/payment/failure/")


# ===== PRODUCTION SECURITY SETTINGS =====
# Enable these in production (when DEBUG=False)
if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Additional security headers
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
    }
    
    # X-Frame-Options
    X_FRAME_OPTIONS = "DENY"
